### ISSUE TITLE
Scala 2.10 Support

### ISSUE THREAD

**Issue by bpholt** [MonsantoCo/cloudformation-template-generator#86]
It would be helpful to build this project for Scala 2.10 to enable more easily using it from sbt. For example, we have Scala services that are assembled to either jars uploaded to S3 (e.g. for AWS Lambda functions) or Docker images published to our private Docker registry. In both cases, the publishing happens from an sbt plugin. It would be great to define a CloudFormation stack as part of the build and have it created or updated by executing something like `sbt deploy`.

However, since sbt is essentially a version behind Scala itself (sbt 0.13 is compiled with Scala 2.10), it's not easy to include this library as a dependency of an sbt 0.13 plugin. I'm working around it now by including the CloudFormation code as a sub-project that writes the template to a local file. sbt runs the sub-project, reads in the generated file, and then uses the AWS SDK to create or update the CloudFormation stack. This is inconvenient in several ways, as you can imagine.

I tried compiling the library using 2.10, but ran into problems with case classes with more than 22 parameters. Before I try refactoring those case classes, I wanted to get some feedback on the overall goal, and whether, in the end, you're open to supporting Scala 2.10.

**Comment by tj-corrigan** [comment]
In general I'd be supportive of cross-compiling to scala 2.10. 

Looks like there are 2 case classes with more than 22 parameters: `AWS::RDS::DBInstance` and  `AWS::Redshift::Cluster`. We can't really change the structure of them though since they need to match the JSON serialization Amazon is expecting. I suppose we could nest them and build custom serializers. Perhaps we could also make them regular classes or make? Either way I'm guessing we will be breaking backwards compatibility unless we make a separate 2.10 branch that would need to be maintained.

I'm open to suggestions here.

**Comment by tj-corrigan** [comment]
Based off conversation in #92 I'm going to close this as a won't fix for now.
